"""Load closed contour points generated by tempest-extremes and associate points with
track points
"""

import huracanpy
import numpy as np
import pandas as pd
from tqdm import tqdm
import xarray as xr


def main(tracks_fname, nodes_fname, start_year):
    # Split by year due to memory use
    for year in tqdm(range(start_year, 2024 + 1)):
        tracks = huracanpy.load(tracks_fname)
        tracks = tracks.isel(record=tracks.time.dt.year == year)
        nodes = load_nodefile(nodes_fname)
        nodes = nodes[nodes.time.dt.year == year]

        tracks_df = tracks[["track_id", "lon", "lat", "time"]].to_dataframe()

        # Save the record value to insert values back into the tracks later
        tracks_df["record"] = tracks_df.index.values

        # Record values also used for removing duplicates
        # (multiple points matching single points)
        # So keep a record equivalent for the nodes
        nodes["id"] = nodes.index.values

        # Largely copying huracanpy.assess.match
        # Find all point where a track point is with 5-degrees of an MSLP minima
        merged = pd.merge(tracks_df, nodes, on="time").drop_duplicates()
        merged["distance"] = (
            huracanpy.calc.distance(
                merged.lon_x, merged.lat_x, merged.lon_y, merged.lat_y, method="geod"
            )
            * 1e-3
        )
        merged = merged[merged.distance <= 550]

        # Where the same track point matches multiple MSLP minima, keep the closest one
        merged = remove_duplicates_by_distance(merged, "record")

        # If two track points match the same MSLP minima, only keep the closest
        merged = remove_duplicates_by_distance(merged, "id")

        # Add MSLP minima back to tracks
        # Default to NaN where there is no minima associated to the track points
        tracks["mslp_minima"] = ("record", np.full(len(tracks.record), np.nan))
        tracks["mslp_minima_lon"] = ("record", np.full(len(tracks.record), np.nan))
        tracks["mslp_minima_lat"] = ("record", np.full(len(tracks.record), np.nan))

        tracks.mslp_minima.loc[merged.record.values] = merged.mslp_anomaly
        tracks.mslp_minima_lon.loc[merged.record.values] = merged.lon_y
        tracks.mslp_minima_lat.loc[merged.record.values] = merged.lat_y

        tracks.to_netcdf(f"{tracks_fname.split('.')[0]}_{year}.nc")

    tracks = []
    for year in tqdm(range(start_year, 2024 + 1)):
        tracks.append(xr.open_dataset(f"{tracks_fname.split('.')[0]}_{year}.nc"))

    tracks = xr.concat(tracks, dim="record").sortby(["track_id", "time"])
    huracanpy.save(tracks, f"{tracks_fname.split('.')[0]}-mslp.nc")


def load_nodefile(filename):
    df = pd.read_csv(
        filename,
        sep="\t",
        header=None,
        names=["blank", "i", "j", "lon", "lat", "mslp_anomaly"],
    )

    # Nodefile is almost a CSV file but is broken up by the timestamps
    # When loaded with read_csv, they are read into the data columns
    # Extract these rows and add time back to each row using the indices
    time_rows = df[~df.blank.isna()]
    nodes = df.drop(time_rows.index)
    times = pd.to_datetime(
        dict(
            year=time_rows.blank, month=time_rows.i, day=time_rows.j, hour=time_rows.lat
        )
    )

    nodes["time"] = np.zeros(len(nodes), dtype=times.dtype)
    for n, time in enumerate(times):
        if n == len(times) - 1:
            end = nodes.index[-1] + 1
        else:
            end = time_rows.index[n + 1]
        nodes.loc[slice(time_rows.index[n] + 1, end), "time"] = time

    return nodes[["time", "lon", "lat", "mslp_anomaly"]]


def remove_duplicates_by_distance(df, subset):
    duplicates = df.duplicated(subset=subset, keep=False)
    idx_to_keep = []
    for _, rows in df[duplicates].groupby(subset):
        idx_to_keep.append(rows.index.values[rows.distance.argmin()])

    # Pick all non duplicates and closest among duplicates
    # Keep closest by setting duplicate bool to false for closest ones
    duplicates.loc[idx_to_keep] = False
    return df[~duplicates]


if __name__ == "__main__":
    main("ERA5_all.nc", "era5_mslp-nodes.csv", start_year=1940)
    main("JRA3Q_nolat-nwc-tcident.nc", "jra3q_mslp-nodes.csv", start_year=1948)
